# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - functions
#   - deploy
#   - hello_world
#   - --source=.
#   - --trigger-http
#   - --runtime=python37
#   - --allow-unauthenticated


steps:
- name: 'gcr.io/ecstatic-backup-319018/terraform'
  args: ['init',
    '-backend-config=project=ecstatic-backup-319018',
    '-backend-config=bucket=BUCKET-NAME']
  env:
    - "TF_VAR_project-name=ecstatic-backup-319018"

- name: 'gcr.io/ecstatic-backup-319018/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=ecstatic-backup-319018"

- name: 'gcr.io/ecstatic-backup-319018/terraform'
  args: ['apply', '-auto-approve']
  env:
    - "TF_VAR_project-name=ecstatic-backup-319018"
