# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - functions
#   - deploy
#   - hello_world
#   - --source=.
#   - --trigger-http
#   - --runtime=python37
#   - --allow-unauthenticated #


steps:
#step 1 init
- name: 'gcr.io/ecstatic-backup-319018/terraform'
  args: ['init',
    '-backend-config=project=ecstatic-backup-319018',
    '-backend-config=bucket=ecstatic-backup-319018-tfstate1']
  env:
    - "TF_VAR_project-name=ecstatic-backup-319018"

#step 2 plan
- name: 'gcr.io/ecstatic-backup-319018/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=ecstatic-backup-319018"

#step 3 apply
- name: 'gcr.io/ecstatic-backup-319018/terraform'
  args: ['apply', '-auto-approve']
  env:
    - "TF_VAR_project-name=ecstatic-backup-319018"
