# integrate tf with cloud build  
# using build steps
# Step 1: runs 'terraform init' command
# Step 2: runs 'terraform plan' command
# Step 3: runs 'terraform apply' command 

steps:
#1
- name: 'hashicorp/terraform:1.0.0'
  args: ['init',
    '-backend-config=project=PROJECTID',
    '-backend-config=bucketPROJECTID-tfstate']
  env:
    - "TF_VAR_project-name=PROJECTID"

#2
- name: 'hashicorp/terraform:1.0.0'
  args: ['plan']
  env:
    - "TF_VAR_project-name=PROJECTID"

#3
- name: 'hashicorp/terraform:1.0.0'
  args: ['apply', '-auto-approve']
  env:
    - "TF_VAR_project-name=PROJECTID"
